matrix:
  include:
    - os: linux
      env: FISH=2
      addons:
        apt:
          sources:
            - sourceline: "ppa:fish-shell/release-2"
          packages:
            - fish
    - os: linux
      env: FISH=3
      addons:
        apt:
          sources:
            - sourceline: "ppa:fish-shell/release-3"
          packages:
            - fish
    - os: osx
      env: FISH=2
      addons:
        homebrew:
          packages:
            - 'test/Homebrew-Formula-fish-2.7.1.rb'
          update: true # TODO: build should be green without, but isn't
    - os: osx
      env: FISH=3
      addons:
        homebrew:
          packages:
            - fish # --> latest, i.e. >=3.0.2
          update: true # TODO: build should be green without, but isn't

sudo: required
before_install:
  - curl -s "https://get.sdkman.io" | bash
  - bash test/prepare_tests.sh

install:
  - mkdir -p "${HOME}"/.config/fish/{completions,conf.d,functions}
  - cp completions/* "${HOME}"/.config/fish/completions/
  - cp conf.d/* "${HOME}"/.config/fish/conf.d/
  - cp functions/* "${HOME}"/.config/fish/functions/
  - uname -a; fish --version

script:
  - ruby test/completion.rb
  - fish test/wrapper.fish
  - fish test/reinitialize.fish
  - bash -c "source \"${HOME}/.sdkman/bin/sdkman-init.sh\" && sdk install crash 1.3.0 && sdk uninstall crash 1.3.0" && fish test/10_zombies_new.fish
  - bash -c "rm -rf \"${HOME}/.sdkman\" &&  sed -i 's/^.*\(sdkman\|SDKMAN\).*$//g' \"${HOME}/.bashrc\" && echo 'SDKMAN uninstalled'" && fish -c "echo 'y' | sdk" && fish -c "sdk version"
