env:
  - FISH=release-2
  - FISH=release-3

sudo: required
before_install:
  - sudo add-apt-repository -y ppa:fish-shell/${FISH}
  - sudo apt-get update
  - sudo apt-get -y install fish
  - curl -s "https://get.sdkman.io" | bash
  - bash test/prepare_tests.sh

install:
  - mkdir -p "${HOME}"/.config/fish/{completions,conf.d,functions}
  - cp completions/* "${HOME}"/.config/fish/completions/
  - cp conf.d/* "${HOME}"/.config/fish/conf.d/
  - cp functions/* "${HOME}"/.config/fish/functions/
  - uname -a; fish --version

script:
  - ruby test/completion.rb
  - fish test/wrapper.fish
  - fish test/reinitialize.fish
  - bash -c "source ${HOME}/.sdkman/bin/sdkman-init.sh && sdk install crash 1.3.0 && sdk uninstall crash 1.3.0" && fish test/10_zombies_new.fish
  - bash -c "rm -rf ~/.sdkman &&  sed -i 's/^.*\(sdkman\|SDKMAN\).*$//g' ~/.bashrc && echo 'SDKMAN uninstalled'" && fish -c "echo 'y' | sdk" && fish -c "sdk version"
